#define _CRT_SECURE_NO_WARNINGS
#include <stdio.h>
#include <assert.h>
#include <stdlib.h>

const char *subject_ids[] = {
    "1002", "1003", "1004", "1005", "1006", "1007", "1008", "1009",
    "1012", "1013", "1014", "1015", "1016", "1017", "1018", "1020",
    "1021", "1022", "1023", "1025", "1026", "1028", "1029", "1030",
    "1031", "1032", "1033", "1034", "1037", "1038", "1039", "1040",
    "1041", "1042", "1043", "1044", "1045", "1046", "1047", "1048",
    "1049", "1050", "1051", "1052", "1053", "1054", "1055", "1056",
    "1057", "1058", "1059"
};

void make_def_file(const char *filename, const char *subject_id, int sample_rate);

int main()
{
    const char *subject_id;
    const int sample_rate = 44100;  // dependent on HRIR data
    int arr_count = sizeof(subject_ids)/sizeof(subject_ids[0]);
    for (int i = 0; i < arr_count; i++) {
        subject_id = subject_ids[i];
        char buf[32] = { 0 };
        snprintf(buf, sizeof(buf), "bin/hrtf_defs/IRC_%s.def", subject_id);
        make_def_file(buf, subject_id, sample_rate);
    }
    for (int i = 0; i < arr_count; i++) {
        subject_id = subject_ids[i];
        char buf[128] = { 0 };
        snprintf(buf, sizeof(buf), "cd bin/hrtf_defs && makehrtf.exe -i IRC_%s.def -o oalsoft_hrtf_%s-%d.mhr", subject_id, subject_id, sample_rate);
        system(buf);
    }
    printf("fin.\n");
    int fix_unused_warning = getchar();
    return 0 * fix_unused_warning;
}

void make_def_file(const char *filename, const char *subject_id, int sample_rate) {
    FILE *f = fopen(filename, "w");
    assert(f);
    fprintf(f, "# This is a makehrtf HRIR definition file.  It is used to define the layout\n");
    fprintf(f, "# and source data to be processed into an OpenAL Soft compatible HRTF.\n");
    fprintf(f, "#\n");
    fprintf(f, "# This definition is used to transform the left and right ear HRIRs of any\n");
    fprintf(f, "# raw data set from the IRCAM/AKG Listen HRTF database.\n");
    fprintf(f, "#\n");
    fprintf(f, "# The data sets are available free of charge from:\n");
    fprintf(f, "#\n");
    fprintf(f, "#  http://recherche.ircam.fr/equipes/salles/listen/index.html\n");
    fprintf(f, "#\n");
    fprintf(f, "# Contact for the Listen HRTF Database:\n");
    fprintf(f, "#\n");
    fprintf(f, "#  Olivier Warusfel <olivier.warusfel@ircam.fr>,\n");
    fprintf(f, "#  Room Acoustics Team, IRCAM\n");
    fprintf(f, "#  1, place Igor Stravinsky\n");
    fprintf(f, "#  75004 PARIS, France\n");
    fprintf(f, "\n");
    fprintf(f, "rate     = %d\n", sample_rate);
    fprintf(f, "\n");
    fprintf(f, "# The IRCAM sets are stereo because they provide both ear HRIRs.\n");
    fprintf(f, "type     = stereo\n");
    fprintf(f, "\n");
    fprintf(f, "# The raw sets have up to 8192 samples, but 2048 seems large enough.\n");
    fprintf(f, "points   = 2048\n");
    fprintf(f, "\n");
    fprintf(f, "# No head radius was provided.  Just use the average radius of 9 cm.\n");
    fprintf(f, "radius   = 0.09\n");
    fprintf(f, "\n");
    fprintf(f, "# The IRCAM sets are single-field (like most others) with a distance between\n");
    fprintf(f, "# the source and the listener of 1.95 meters.\n");
    fprintf(f, "distance = 1.95\n");
    fprintf(f, "\n");
    fprintf(f, "# This set isn't as dense as the MIT set.\n");
    fprintf(f, "azimuths = 1, 6, 12, 24, 24, 24, 24, 24, 24, 24, 12, 6, 1\n");
    fprintf(f, "\n");
    fprintf(f, "# The IRCAM source azimuth is counter-clockwise, so it needs to be flipped.\n");
    fprintf(f, "# Left and right ear HRIRs (from the respective WAVE channels) are used to\n");
    fprintf(f, "# create a stereo HRTF.\n");
    fprintf(f, "\n");
    fprintf(f, "# Replace all occurrences of IRC_#### for the desired subject (%s was used\n", subject_id);
    fprintf(f, "# in this demonstration).\n");
    fprintf(f, "[  3,  0 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T000_P315.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T000_P315.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  3,  1 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T345_P315.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T345_P315.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  3,  2 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T330_P315.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T330_P315.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  3,  3 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T315_P315.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T315_P315.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  3,  4 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T300_P315.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T300_P315.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  3,  5 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T285_P315.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T285_P315.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  3,  6 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T270_P315.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T270_P315.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  3,  7 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T255_P315.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T255_P315.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  3,  8 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T240_P315.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T240_P315.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  3,  9 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T225_P315.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T225_P315.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  3, 10 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T210_P315.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T210_P315.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  3, 11 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T195_P315.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T195_P315.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  3, 12 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T180_P315.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T180_P315.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  3, 13 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T165_P315.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T165_P315.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  3, 14 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T150_P315.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T150_P315.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  3, 15 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T135_P315.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T135_P315.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  3, 16 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T120_P315.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T120_P315.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  3, 17 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T105_P315.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T105_P315.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  3, 18 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T090_P315.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T090_P315.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  3, 19 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T075_P315.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T075_P315.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  3, 20 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T060_P315.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T060_P315.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  3, 21 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T045_P315.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T045_P315.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  3, 22 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T030_P315.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T030_P315.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  3, 23 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T015_P315.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T015_P315.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "\n");
    fprintf(f, "[  4,  0 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T000_P330.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T000_P330.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  4,  1 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T345_P330.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T345_P330.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  4,  2 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T330_P330.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T330_P330.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  4,  3 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T315_P330.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T315_P330.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  4,  4 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T300_P330.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T300_P330.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  4,  5 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T285_P330.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T285_P330.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  4,  6 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T270_P330.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T270_P330.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  4,  7 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T255_P330.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T255_P330.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  4,  8 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T240_P330.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T240_P330.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  4,  9 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T225_P330.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T225_P330.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  4, 10 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T210_P330.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T210_P330.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  4, 11 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T195_P330.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T195_P330.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  4, 12 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T180_P330.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T180_P330.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  4, 13 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T165_P330.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T165_P330.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  4, 14 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T150_P330.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T150_P330.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  4, 15 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T135_P330.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T135_P330.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  4, 16 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T120_P330.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T120_P330.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  4, 17 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T105_P330.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T105_P330.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  4, 18 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T090_P330.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T090_P330.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  4, 19 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T075_P330.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T075_P330.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  4, 20 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T060_P330.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T060_P330.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  4, 21 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T045_P330.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T045_P330.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  4, 22 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T030_P330.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T030_P330.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  4, 23 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T015_P330.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T015_P330.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "\n");
    fprintf(f, "[  5,  0 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T000_P345.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T000_P345.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  5,  1 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T345_P345.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T345_P345.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  5,  2 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T330_P345.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T330_P345.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  5,  3 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T315_P345.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T315_P345.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  5,  4 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T300_P345.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T300_P345.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  5,  5 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T285_P345.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T285_P345.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  5,  6 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T270_P345.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T270_P345.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  5,  7 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T255_P345.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T255_P345.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  5,  8 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T240_P345.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T240_P345.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  5,  9 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T225_P345.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T225_P345.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  5, 10 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T210_P345.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T210_P345.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  5, 11 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T195_P345.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T195_P345.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  5, 12 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T180_P345.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T180_P345.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  5, 13 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T165_P345.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T165_P345.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  5, 14 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T150_P345.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T150_P345.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  5, 15 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T135_P345.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T135_P345.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  5, 16 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T120_P345.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T120_P345.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  5, 17 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T105_P345.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T105_P345.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  5, 18 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T090_P345.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T090_P345.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  5, 19 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T075_P345.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T075_P345.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  5, 20 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T060_P345.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T060_P345.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  5, 21 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T045_P345.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T045_P345.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  5, 22 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T030_P345.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T030_P345.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  5, 23 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T015_P345.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T015_P345.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "\n");
    fprintf(f, "[  6,  0 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T000_P000.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T000_P000.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  6,  1 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T345_P000.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T345_P000.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  6,  2 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T330_P000.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T330_P000.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  6,  3 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T315_P000.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T315_P000.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  6,  4 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T300_P000.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T300_P000.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  6,  5 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T285_P000.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T285_P000.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  6,  6 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T270_P000.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T270_P000.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  6,  7 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T255_P000.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T255_P000.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  6,  8 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T240_P000.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T240_P000.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  6,  9 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T225_P000.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T225_P000.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  6, 10 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T210_P000.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T210_P000.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  6, 11 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T195_P000.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T195_P000.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  6, 12 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T180_P000.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T180_P000.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  6, 13 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T165_P000.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T165_P000.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  6, 14 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T150_P000.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T150_P000.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  6, 15 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T135_P000.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T135_P000.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  6, 16 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T120_P000.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T120_P000.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  6, 17 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T105_P000.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T105_P000.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  6, 18 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T090_P000.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T090_P000.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  6, 19 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T075_P000.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T075_P000.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  6, 20 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T060_P000.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T060_P000.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  6, 21 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T045_P000.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T045_P000.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  6, 22 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T030_P000.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T030_P000.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  6, 23 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T015_P000.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T015_P000.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "\n");
    fprintf(f, "[  7,  0 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T000_P015.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T000_P015.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  7,  1 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T345_P015.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T345_P015.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  7,  2 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T330_P015.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T330_P015.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  7,  3 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T315_P015.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T315_P015.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  7,  4 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T300_P015.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T300_P015.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  7,  5 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T285_P015.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T285_P015.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  7,  6 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T270_P015.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T270_P015.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  7,  7 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T255_P015.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T255_P015.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  7,  8 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T240_P015.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T240_P015.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  7,  9 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T225_P015.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T225_P015.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  7, 10 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T210_P015.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T210_P015.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  7, 11 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T195_P015.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T195_P015.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  7, 12 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T180_P015.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T180_P015.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  7, 13 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T165_P015.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T165_P015.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  7, 14 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T150_P015.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T150_P015.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  7, 15 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T135_P015.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T135_P015.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  7, 16 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T120_P015.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T120_P015.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  7, 17 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T105_P015.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T105_P015.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  7, 18 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T090_P015.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T090_P015.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  7, 19 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T075_P015.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T075_P015.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  7, 20 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T060_P015.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T060_P015.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  7, 21 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T045_P015.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T045_P015.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  7, 22 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T030_P015.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T030_P015.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  7, 23 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T015_P015.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T015_P015.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "\n");
    fprintf(f, "[  8,  0 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T000_P030.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T000_P030.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  8,  1 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T345_P030.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T345_P030.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  8,  2 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T330_P030.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T330_P030.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  8,  3 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T315_P030.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T315_P030.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  8,  4 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T300_P030.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T300_P030.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  8,  5 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T285_P030.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T285_P030.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  8,  6 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T270_P030.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T270_P030.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  8,  7 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T255_P030.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T255_P030.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  8,  8 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T240_P030.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T240_P030.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  8,  9 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T225_P030.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T225_P030.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  8, 10 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T210_P030.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T210_P030.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  8, 11 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T195_P030.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T195_P030.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  8, 12 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T180_P030.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T180_P030.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  8, 13 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T165_P030.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T165_P030.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  8, 14 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T150_P030.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T150_P030.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  8, 15 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T135_P030.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T135_P030.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  8, 16 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T120_P030.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T120_P030.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  8, 17 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T105_P030.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T105_P030.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  8, 18 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T090_P030.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T090_P030.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  8, 19 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T075_P030.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T075_P030.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  8, 20 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T060_P030.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T060_P030.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  8, 21 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T045_P030.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T045_P030.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  8, 22 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T030_P030.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T030_P030.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  8, 23 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T015_P030.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T015_P030.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "\n");
    fprintf(f, "[  9,  0 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T000_P045.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T000_P045.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  9,  1 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T345_P045.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T345_P045.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  9,  2 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T330_P045.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T330_P045.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  9,  3 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T315_P045.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T315_P045.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  9,  4 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T300_P045.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T300_P045.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  9,  5 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T285_P045.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T285_P045.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  9,  6 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T270_P045.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T270_P045.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  9,  7 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T255_P045.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T255_P045.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  9,  8 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T240_P045.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T240_P045.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  9,  9 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T225_P045.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T225_P045.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  9, 10 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T210_P045.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T210_P045.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  9, 11 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T195_P045.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T195_P045.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  9, 12 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T180_P045.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T180_P045.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  9, 13 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T165_P045.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T165_P045.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  9, 14 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T150_P045.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T150_P045.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  9, 15 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T135_P045.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T135_P045.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  9, 16 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T120_P045.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T120_P045.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  9, 17 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T105_P045.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T105_P045.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  9, 18 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T090_P045.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T090_P045.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  9, 19 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T075_P045.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T075_P045.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  9, 20 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T060_P045.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T060_P045.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  9, 21 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T045_P045.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T045_P045.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  9, 22 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T030_P045.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T030_P045.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[  9, 23 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T015_P045.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T015_P045.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "\n");
    fprintf(f, "[ 10,  0 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T000_P060.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T000_P060.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[ 10,  1 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T330_P060.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T330_P060.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[ 10,  2 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T300_P060.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T300_P060.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[ 10,  3 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T270_P060.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T270_P060.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[ 10,  4 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T240_P060.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T240_P060.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[ 10,  5 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T210_P060.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T210_P060.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[ 10,  6 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T180_P060.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T180_P060.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[ 10,  7 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T150_P060.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T150_P060.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[ 10,  8 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T120_P060.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T120_P060.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[ 10,  9 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T090_P060.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T090_P060.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[ 10, 10 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T060_P060.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T060_P060.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[ 10, 11 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T030_P060.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T030_P060.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "\n");
    fprintf(f, "[ 11,  0 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T000_P075.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T000_P075.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[ 11,  1 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T300_P075.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T300_P075.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[ 11,  2 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T240_P075.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T240_P075.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[ 11,  3 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T180_P075.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T180_P075.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[ 11,  4 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T120_P075.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T120_P075.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "[ 11,  5 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T060_P075.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T060_P075.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "\n");
    fprintf(f, "[ 12,  0 ] = wave (0) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T000_P090.wav\" left\n", subject_id, subject_id, subject_id);
    fprintf(f, "           + wave (1) : \"../hrtf_raw/IRC_%s/RAW/WAV/IRC_%s_R/IRC_%s_R_R0195_T000_P090.wav\" right\n", subject_id, subject_id, subject_id);
    fprintf(f, "\n");
    fprintf(f, "\n");
    fclose(f);
}